﻿version: '3.9'

services:
  backend:
    build: ./backend
    container_name: blue_archive_calc_backend
    command: >

    volumes:
      - ./backend:/app  # ローカルのコードをコンテナに同期
    ports:
      - "8000:8000"
    depends_on:
      - db  # DB コンテナが起動後に実行
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  db:
    image: postgres:15
    container_name: shifts_postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # DB データの永続化

  frontend:
    build: ./frontend
    container_name: blue_archive_calc_frontend
    ports:
      - "5173:5173"  # Vite 用ポート
    volumes:
      - ./frontend:/app
      - /app/node_modules  # node_modules をコンテナ内に保持
    depends_on:
      - backend  # Django 起動後にフロントエンドを起動
    # TODO: 下記の起動確認完了後、コメントアウトを外す
    # command: >
    #   sh -c "npm install && npm run dev -- --host 0.0.0.0"
    # tty: true

volumes:
  postgres_data:  # DB のデータ永続化用